import "./globals.css"
import type { Metadata } from "next"
import { Varela_Round } from "next/font/google"

const varelaRound = Varela_Round({ weight: "400", subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={varelaRound.className}>{children}</body>
    </html>
  )
}
